# Generated by Django 4.2.11 on 2024-03-16 20:56

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_author_event_content_event_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='back_content',
            field=models.TextField(default='Date: {date}\nTime: {time}\nLocation: {location}\nDescription: {description}\nSpeaker: {speaker}'),
        ),
        migrations.AddField(
            model_name='event',
            name='front_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
