# Generated by Django 4.2.11 on 2024-03-25 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_event_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(default='Default location', max_length=75),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(max_length=75, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='speaker',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=75),
        ),
    ]
